CREATE TABLE TABELA_CLIENTES (
CPF VARCHAR(11), /*Apenas com números, sem pontos ou hífens*/
NOME VARCHAR(100),
ENDERECO_RUA VARCHAR(150),
ENDERECO_BAIRRO VARCHAR(150),
ENDERECO_CIDADE VARCHAR(150),
ENDERECO_COMPLEMENTO VARCHAR(30),
CEP VARCHAR(8),
IDADE SMALLINT,tabela_clientes
SEXO VARCHAR(1), /*M ou F*/
LIMITE_CREDITO FLOAT,
VOLUME_MINIMO_COMPRAS FLOAT,
JA_REALIZOU_PRIMEIRA_COMPRA BIT); /* 1 -> já realizou, 0 -> não realizou*/